CREATE TABLE IF NOT EXISTS inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku_code VARCHAR(255) NOT NULL UNIQUE,
  quantity INT NOT NULL
);

MERGE INTO inventory (sku_code, quantity) KEY (sku_code)
VALUES ('iphone_13', 10), ('iphone_13_red', 0);
