spring.application.name=api-gateway
server.port=8080

# ==========================================================
# 1. TẮT HOÀN TOÀN EUREKA
# ==========================================================
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# ==========================================================
# 2. ĐỊNH TUYẾN GIẢ LẬP ĐỂ TEST ĐỘC LẬP 
# ==========================================================
# Chúng ta sẽ cấu hình Gateway lấy dữ liệu từ một trang web test trên mạng (jsonplaceholder)
spring.cloud.gateway.routes[0].id=test-service-online
spring.cloud.gateway.routes[0].uri=https://jsonplaceholder.typicode.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/posts/**

# ==========================================================
# 3. CẤU HÌNH GỐC 
# ==========================================================
# spring.cloud.gateway.routes[1].id=product-service
# spring.cloud.gateway.routes[1].uri=lb://product-service
# spring.cloud.gateway.routes[1].predicates[0]=Path=/api/product/**

# ==========================================================
# 4. GIÁM SÁT HỆ THỐNG
# ==========================================================
management.endpoints.web.exposure.include=*
```