# Tên ứng dụng
spring.application.name=product-service
# Cổng chạy ứng dụng
server.port=8080

# Cấu hình kết nối MongoDB (theo yêu cầu mục 3 trang 2)
# Nếu bạn chạy MongoDB local, hãy đảm bảo port 27017 đang mở
spring.data.mongodb.uri=mongodb://localhost:27017/product-db

# Cấu hình Actuator & Prometheus (theo yêu cầu mục 4 trang 2) [cite: 44, 47, 48]
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always